1.0
vladimirrim/java_hw pull request #12
Opened 2017-11-14 17:57 UTC by vladimirrim

2017-11-28 16:03 UTC, jzuken requested changes

2017-11-28 16:03 UTC, jzuken commented on TreeSet/src/main/java/ru/spbau/egorov/hw_7/set/Set.java
> +            if (cmpt.compareTo(cur.value) == 0)
так давайте в конструкторе без аргументов проинициализируем компаратор, чтобы он использовал compareTo(), тогда не надо будет проверок лишних делать

2017-11-28 16:03 UTC, jzuken commented on TreeSet/src/main/java/ru/spbau/egorov/hw_7/tree_set/TreeSet.java
> +    private Set<E> tree;
так может тогда переменуем Set в Tree? потому как оно на самом деле дерево

2017-11-28 16:03 UTC, jzuken commented on TreeSet/src/main/java/ru/spbau/egorov/hw_7/tree_set/TreeSet.java
> +public class TreeSet<E> extends AbstractSet<E> implements MyTreeSet<E> {
доки?

2017-12-20 14:10 UTC, jzuken requested changes

2017-12-20 14:10 UTC, jzuken commented on TreeSet/src/main/java/ru/spbau/egorov/hw_7/tree_set/TreeSet.java
> +        tree = new Tree<>();
а чего бы и здесь тоже компаратор не передать в дерево? вы ж там по сути то же самое делаете. или исправлять надо только то, на что я замечание напишу? 
-1

2017-12-26 10:06 UTC, jzuken requested changes

2017-12-26 10:06 UTC, jzuken commented on TreeSet/src/main/java/ru/spbau/egorov/hw_7/tree/Tree.java
> +        comparator = (Comparator<T>) (o1, o2) -> ((Comparable<? super T>) o1).compareTo(o2);
Владимир, вы издеваетесь? а это тут теперь зачем? неужто нельзя один раз аккуратно всё поправить?
-1

2017-12-26 10:13 UTC, vladimirrim commented on TreeSet/src/main/java/ru/spbau/egorov/hw_7/tree/Tree.java
> +        comparator = (Comparator<T>) (o1, o2) -> ((Comparable<? super T>) o1).compareTo(o2);
Зачем лишать дефолтного конструктора независищий от TreeSet класс?

2017-12-26 11:03 UTC, jzuken commented on TreeSet/src/main/java/ru/spbau/egorov/hw_7/tree/Tree.java
> +        comparator = (Comparator<T>) (o1, o2) -> ((Comparable<? super T>) o1).compareTo(o2);
ладно, видимо тут я действительно не прав. замечание снимается

2017-12-26 11:03 UTC, merged